/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as TransportRouteImport } from './routes/transport'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PrototypesRouteImport } from './routes/prototypes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MapRouteImport } from './routes/map'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as JoinRouteImport } from './routes/join'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as DirectoryIndexRouteImport } from './routes/directory/index'
import { Route as CommandIndexRouteImport } from './routes/command.index'
import { Route as CasesIndexRouteImport } from './routes/cases.index'
import { Route as CIndexRouteImport } from './routes/c.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPeopleRouteImport } from './routes/settings.people'
import { Route as SettingsOrgRouteImport } from './routes/settings.org'
import { Route as DriveIdRouteImport } from './routes/drive.$id'
import { Route as DirectoryImportRouteImport } from './routes/directory/import'
import { Route as CommandIdRouteImport } from './routes/command.$id'
import { Route as CasesIdRouteImport } from './routes/cases.$id'
import { Route as CMatchRouteImport } from './routes/c.match'
import { Route as CManageRouteImport } from './routes/c.manage'
import { Route as DirectoryVolunteerIdRouteImport } from './routes/directory/volunteer.$id'
import { Route as DirectoryResourceIdRouteImport } from './routes/directory/resource.$id'
import { Route as DirectoryRequestIdRouteImport } from './routes/directory/request.$id'
import { Route as DirectoryReportIdRouteImport } from './routes/directory/report.$id'
import { Route as DirectoryPersonIdRouteImport } from './routes/directory/person.$id'
import { Route as DirectoryOrgIdRouteImport } from './routes/directory/org.$id'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportRoute = TransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypesRoute = PrototypesRouteImport.update({
  id: '/prototypes',
  path: '/prototypes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const DirectoryIndexRoute = DirectoryIndexRouteImport.update({
  id: '/directory/',
  path: '/directory/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIndexRoute = CommandIndexRouteImport.update({
  id: '/command/',
  path: '/command/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CIndexRoute = CIndexRouteImport.update({
  id: '/c/',
  path: '/c/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPeopleRoute = SettingsPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrgRoute = SettingsOrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => SettingsRoute,
} as any)
const DriveIdRoute = DriveIdRouteImport.update({
  id: '/drive/$id',
  path: '/drive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryImportRoute = DirectoryImportRouteImport.update({
  id: '/directory/import',
  path: '/directory/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIdRoute = CommandIdRouteImport.update({
  id: '/command/$id',
  path: '/command/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIdRoute = CasesIdRouteImport.update({
  id: '/cases/$id',
  path: '/cases/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CMatchRoute = CMatchRouteImport.update({
  id: '/c/match',
  path: '/c/match',
  getParentRoute: () => rootRouteImport,
} as any)
const CManageRoute = CManageRouteImport.update({
  id: '/c/manage',
  path: '/c/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryVolunteerIdRoute = DirectoryVolunteerIdRouteImport.update({
  id: '/directory/volunteer/$id',
  path: '/directory/volunteer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryResourceIdRoute = DirectoryResourceIdRouteImport.update({
  id: '/directory/resource/$id',
  path: '/directory/resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRequestIdRoute = DirectoryRequestIdRouteImport.update({
  id: '/directory/request/$id',
  path: '/directory/request/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryReportIdRoute = DirectoryReportIdRouteImport.update({
  id: '/directory/report/$id',
  path: '/directory/report/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryPersonIdRoute = DirectoryPersonIdRouteImport.update({
  id: '/directory/person/$id',
  path: '/directory/person/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryOrgIdRoute = DirectoryOrgIdRouteImport.update({
  id: '/directory/org/$id',
  path: '/directory/org/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inventory': typeof InventoryRoute
  '/join': typeof JoinRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/prototypes': typeof PrototypesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transport': typeof TransportRoute
  '/volunteers': typeof VolunteersRoute
  '/c/manage': typeof CManageRoute
  '/c/match': typeof CMatchRoute
  '/cases/$id': typeof CasesIdRoute
  '/command/$id': typeof CommandIdRoute
  '/directory/import': typeof DirectoryImportRoute
  '/drive/$id': typeof DriveIdRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/people': typeof SettingsPeopleRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/c/': typeof CIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/command/': typeof CommandIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/directory/org/$id': typeof DirectoryOrgIdRoute
  '/directory/person/$id': typeof DirectoryPersonIdRoute
  '/directory/report/$id': typeof DirectoryReportIdRoute
  '/directory/request/$id': typeof DirectoryRequestIdRoute
  '/directory/resource/$id': typeof DirectoryResourceIdRoute
  '/directory/volunteer/$id': typeof DirectoryVolunteerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inventory': typeof InventoryRoute
  '/join': typeof JoinRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/prototypes': typeof PrototypesRoute
  '/reports': typeof ReportsRoute
  '/transport': typeof TransportRoute
  '/volunteers': typeof VolunteersRoute
  '/c/manage': typeof CManageRoute
  '/c/match': typeof CMatchRoute
  '/cases/$id': typeof CasesIdRoute
  '/command/$id': typeof CommandIdRoute
  '/directory/import': typeof DirectoryImportRoute
  '/drive/$id': typeof DriveIdRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/people': typeof SettingsPeopleRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/c': typeof CIndexRoute
  '/cases': typeof CasesIndexRoute
  '/command': typeof CommandIndexRoute
  '/directory': typeof DirectoryIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/directory/org/$id': typeof DirectoryOrgIdRoute
  '/directory/person/$id': typeof DirectoryPersonIdRoute
  '/directory/report/$id': typeof DirectoryReportIdRoute
  '/directory/request/$id': typeof DirectoryRequestIdRoute
  '/directory/resource/$id': typeof DirectoryResourceIdRoute
  '/directory/volunteer/$id': typeof DirectoryVolunteerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/inventory': typeof InventoryRoute
  '/join': typeof JoinRoute
  '/manage': typeof ManageRoute
  '/map': typeof MapRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/prototypes': typeof PrototypesRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRouteWithChildren
  '/transport': typeof TransportRoute
  '/volunteers': typeof VolunteersRoute
  '/c/manage': typeof CManageRoute
  '/c/match': typeof CMatchRoute
  '/cases/$id': typeof CasesIdRoute
  '/command/$id': typeof CommandIdRoute
  '/directory/import': typeof DirectoryImportRoute
  '/drive/$id': typeof DriveIdRoute
  '/settings/org': typeof SettingsOrgRoute
  '/settings/people': typeof SettingsPeopleRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/c/': typeof CIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/command/': typeof CommandIndexRoute
  '/directory/': typeof DirectoryIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/directory/org/$id': typeof DirectoryOrgIdRoute
  '/directory/person/$id': typeof DirectoryPersonIdRoute
  '/directory/report/$id': typeof DirectoryReportIdRoute
  '/directory/request/$id': typeof DirectoryRequestIdRoute
  '/directory/resource/$id': typeof DirectoryResourceIdRoute
  '/directory/volunteer/$id': typeof DirectoryVolunteerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/inventory'
    | '/join'
    | '/manage'
    | '/map'
    | '/match'
    | '/onboarding'
    | '/prototypes'
    | '/reports'
    | '/settings'
    | '/transport'
    | '/volunteers'
    | '/c/manage'
    | '/c/match'
    | '/cases/$id'
    | '/command/$id'
    | '/directory/import'
    | '/drive/$id'
    | '/settings/org'
    | '/settings/people'
    | '/settings/profile'
    | '/c/'
    | '/cases/'
    | '/command/'
    | '/directory/'
    | '/settings/'
    | '/directory/org/$id'
    | '/directory/person/$id'
    | '/directory/report/$id'
    | '/directory/request/$id'
    | '/directory/resource/$id'
    | '/directory/volunteer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/inventory'
    | '/join'
    | '/manage'
    | '/map'
    | '/match'
    | '/onboarding'
    | '/prototypes'
    | '/reports'
    | '/transport'
    | '/volunteers'
    | '/c/manage'
    | '/c/match'
    | '/cases/$id'
    | '/command/$id'
    | '/directory/import'
    | '/drive/$id'
    | '/settings/org'
    | '/settings/people'
    | '/settings/profile'
    | '/c'
    | '/cases'
    | '/command'
    | '/directory'
    | '/settings'
    | '/directory/org/$id'
    | '/directory/person/$id'
    | '/directory/report/$id'
    | '/directory/request/$id'
    | '/directory/resource/$id'
    | '/directory/volunteer/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/inventory'
    | '/join'
    | '/manage'
    | '/map'
    | '/match'
    | '/onboarding'
    | '/prototypes'
    | '/reports'
    | '/settings'
    | '/transport'
    | '/volunteers'
    | '/c/manage'
    | '/c/match'
    | '/cases/$id'
    | '/command/$id'
    | '/directory/import'
    | '/drive/$id'
    | '/settings/org'
    | '/settings/people'
    | '/settings/profile'
    | '/c/'
    | '/cases/'
    | '/command/'
    | '/directory/'
    | '/settings/'
    | '/directory/org/$id'
    | '/directory/person/$id'
    | '/directory/report/$id'
    | '/directory/request/$id'
    | '/directory/resource/$id'
    | '/directory/volunteer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  InventoryRoute: typeof InventoryRoute
  JoinRoute: typeof JoinRoute
  ManageRoute: typeof ManageRoute
  MapRoute: typeof MapRoute
  MatchRoute: typeof MatchRoute
  OnboardingRoute: typeof OnboardingRoute
  PrototypesRoute: typeof PrototypesRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TransportRoute: typeof TransportRoute
  VolunteersRoute: typeof VolunteersRoute
  CManageRoute: typeof CManageRoute
  CMatchRoute: typeof CMatchRoute
  CasesIdRoute: typeof CasesIdRoute
  CommandIdRoute: typeof CommandIdRoute
  DirectoryImportRoute: typeof DirectoryImportRoute
  DriveIdRoute: typeof DriveIdRoute
  CIndexRoute: typeof CIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  CommandIndexRoute: typeof CommandIndexRoute
  DirectoryIndexRoute: typeof DirectoryIndexRoute
  DirectoryOrgIdRoute: typeof DirectoryOrgIdRoute
  DirectoryPersonIdRoute: typeof DirectoryPersonIdRoute
  DirectoryReportIdRoute: typeof DirectoryReportIdRoute
  DirectoryRequestIdRoute: typeof DirectoryRequestIdRoute
  DirectoryResourceIdRoute: typeof DirectoryResourceIdRoute
  DirectoryVolunteerIdRoute: typeof DirectoryVolunteerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transport': {
      id: '/transport'
      path: '/transport'
      fullPath: '/transport'
      preLoaderRoute: typeof TransportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypes': {
      id: '/prototypes'
      path: '/prototypes'
      fullPath: '/prototypes'
      preLoaderRoute: typeof PrototypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/directory/': {
      id: '/directory/'
      path: '/directory'
      fullPath: '/directory/'
      preLoaderRoute: typeof DirectoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/': {
      id: '/command/'
      path: '/command'
      fullPath: '/command/'
      preLoaderRoute: typeof CommandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/': {
      id: '/c/'
      path: '/c'
      fullPath: '/c/'
      preLoaderRoute: typeof CIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/people': {
      id: '/settings/people'
      path: '/people'
      fullPath: '/settings/people'
      preLoaderRoute: typeof SettingsPeopleRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/org': {
      id: '/settings/org'
      path: '/org'
      fullPath: '/settings/org'
      preLoaderRoute: typeof SettingsOrgRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/drive/$id': {
      id: '/drive/$id'
      path: '/drive/$id'
      fullPath: '/drive/$id'
      preLoaderRoute: typeof DriveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/import': {
      id: '/directory/import'
      path: '/directory/import'
      fullPath: '/directory/import'
      preLoaderRoute: typeof DirectoryImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/$id': {
      id: '/command/$id'
      path: '/command/$id'
      fullPath: '/command/$id'
      preLoaderRoute: typeof CommandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$id': {
      id: '/cases/$id'
      path: '/cases/$id'
      fullPath: '/cases/$id'
      preLoaderRoute: typeof CasesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/match': {
      id: '/c/match'
      path: '/c/match'
      fullPath: '/c/match'
      preLoaderRoute: typeof CMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/manage': {
      id: '/c/manage'
      path: '/c/manage'
      fullPath: '/c/manage'
      preLoaderRoute: typeof CManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/volunteer/$id': {
      id: '/directory/volunteer/$id'
      path: '/directory/volunteer/$id'
      fullPath: '/directory/volunteer/$id'
      preLoaderRoute: typeof DirectoryVolunteerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/resource/$id': {
      id: '/directory/resource/$id'
      path: '/directory/resource/$id'
      fullPath: '/directory/resource/$id'
      preLoaderRoute: typeof DirectoryResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/request/$id': {
      id: '/directory/request/$id'
      path: '/directory/request/$id'
      fullPath: '/directory/request/$id'
      preLoaderRoute: typeof DirectoryRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/report/$id': {
      id: '/directory/report/$id'
      path: '/directory/report/$id'
      fullPath: '/directory/report/$id'
      preLoaderRoute: typeof DirectoryReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/person/$id': {
      id: '/directory/person/$id'
      path: '/directory/person/$id'
      fullPath: '/directory/person/$id'
      preLoaderRoute: typeof DirectoryPersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory/org/$id': {
      id: '/directory/org/$id'
      path: '/directory/org/$id'
      fullPath: '/directory/org/$id'
      preLoaderRoute: typeof DirectoryOrgIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteChildren {
  SettingsOrgRoute: typeof SettingsOrgRoute
  SettingsPeopleRoute: typeof SettingsPeopleRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsOrgRoute: SettingsOrgRoute,
  SettingsPeopleRoute: SettingsPeopleRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  InventoryRoute: InventoryRoute,
  JoinRoute: JoinRoute,
  ManageRoute: ManageRoute,
  MapRoute: MapRoute,
  MatchRoute: MatchRoute,
  OnboardingRoute: OnboardingRoute,
  PrototypesRoute: PrototypesRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TransportRoute: TransportRoute,
  VolunteersRoute: VolunteersRoute,
  CManageRoute: CManageRoute,
  CMatchRoute: CMatchRoute,
  CasesIdRoute: CasesIdRoute,
  CommandIdRoute: CommandIdRoute,
  DirectoryImportRoute: DirectoryImportRoute,
  DriveIdRoute: DriveIdRoute,
  CIndexRoute: CIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  CommandIndexRoute: CommandIndexRoute,
  DirectoryIndexRoute: DirectoryIndexRoute,
  DirectoryOrgIdRoute: DirectoryOrgIdRoute,
  DirectoryPersonIdRoute: DirectoryPersonIdRoute,
  DirectoryReportIdRoute: DirectoryReportIdRoute,
  DirectoryRequestIdRoute: DirectoryRequestIdRoute,
  DirectoryResourceIdRoute: DirectoryResourceIdRoute,
  DirectoryVolunteerIdRoute: DirectoryVolunteerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
